---
- name: Update selected package
  hosts: linux_hosts
  become: true
  gather_facts: true

  tasks:
    - name: Validate package_name
      ansible.builtin.assert:
        that:
          - package_name is defined
          - package_name is match('^[A-Za-z0-9_.:+-]{1,160}$')
        fail_msg: "Set valid package_name."

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
      when: ansible_os_family == "Debian"

    - name: Update package on Debian family
      ansible.builtin.apt:
        name: "{{ package_name }}"
        state: latest
      when: ansible_os_family == "Debian"

    - name: Update package on RedHat family
      ansible.builtin.dnf:
        name: "{{ package_name }}"
        state: latest
      when: ansible_os_family == "RedHat"
