[linux_hosts]
# Замените IP-адреса и пользователя на свои.
# server1 ansible_host=192.168.1.10 ansible_user=danil ansible_become=true
# server2 ansible_host=192.168.1.11 ansible_user=danil ansible_become=true

[linux_hosts:vars]
ansible_python_interpreter=/usr/bin/python3
audit_profile=basic_linux
agent_install_dir=/opt/hcp-agent
